Controllers/ProceduresController.cs
using HyAdmin.AppUtilities;
using HyProvider.HDS;
using HyAdmin.Models.ViewModels;
using HyAdmin.Services;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace HyAdmin.Controllers
{
    public class ProceduresController : Controller
    {
        [AllowAnonymous]
        public ActionResult Index(int Id)
        {
            ViewBag.Id = Id;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Search(string legacyCode, int dependantId, int providerId, string target)
        {
            Token t = new Token();
            t = t.GetToken("");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.SearchProcedureByMemberProvider;

            var client = new RestClient($"{baseURL}{endpoint}/{legacyCode}/{dependantId}/{providerId}/{target}");
            var request = new RestRequest(Method.GET);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/x-www-form-urlencoded");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            request.AddParameter("application/x-www-form-urlencoded", ParameterType.UrlSegment);
            IRestResponse response = client.Execute(request);
            return Json((response.Content), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult GetTariff(string legacyCode, int dependantId, int providerId, string procedureCode)
        {
            Token t = new Token();
            t = t.GetToken("");

            string baseURL = APIServices.BaseURL;
            string endpoint = APIServices.GetTariffByMemberProviderProcedure;

            var client = new RestClient($"{baseURL}{endpoint}/{legacyCode}/{dependantId}/{providerId}/{procedureCode}");
            var request = new RestRequest(Method.GET);
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/x-www-form-urlencoded");
            request.AddHeader("authorization", "Bearer " + t.Tokn);
            request.AddParameter("application/x-www-form-urlencoded", ParameterType.UrlSegment);
            IRestResponse response = client.Execute(request);
            return Json((response.Content), JsonRequestBehavior.AllowGet);
        }
    }

    
}

Views/Procedures/Index.cshtml
@{
    ViewBag.Title = "Procedures Search";
    Layout = "~/Views/Shared/_Semi.cshtml";
}

<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                    <h4 class="m-b-10">Procedures Search</h4>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="#">
                            <i class="feather icon-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Procedures</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Search</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- [ breadcrumb ] end -->

<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">

            <!-- Page body start -->
            <div class="page-body">

                <div class="row">
                    <div class="col-sm-7">

                        <!-- Invoice card start -->
                        <div class="card">
                            <div class="card-block">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <h6>Paramenter Selection</h6>

                                        <img src="https://online.hygeiahmo.com/hydirect/pages/img/loading-balls.svg" class="hide" id="loading" style="width: 40px;float: right; top: -20px; position: relative;" />

                                        <div style="max-height: 500px;overflow: auto;">
                                            <table>
                                                <tr>
                                                    <td>Enrollee Number</td>
                                                    <td><input id="legacyCode" type="text" /></td>
                                                </tr>
                                                <tr>
                                                    <td>Dependant Id</td>
                                                    <td><input id="dependantId" type="text" /></td>
                                                </tr>
                                                <tr class="hide">
                                                    <td>Provider Id</td>
                                                    <td><input id="providerId" type="text" value="@ViewBag.Id" disabled /></td>
                                                </tr>
                                                <tr>
                                                    <td>Procedure</td>
                                                    <td><input id="target" type="text" /></td>
                                                </tr>
                                            </table>
                                        </div>
                                        <button class="btn btn-primary m-b-10 btn-sm waves-effect waves-light m-r-20" onclick="Search()" style="margin-top: 8px">Search</button>

                                        <div class="member-search-result" style="overflow: auto; max-height: 500px;">
                                            <table class="table table-striped table-condensed" style="width: 100%">
                                                <thead>
                                                    <tr>
                                                        <th>Procedure Code</th>
                                                        <th>Procedure Desc</th>
                                                        <th>&nbsp;</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="result"></tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-5">
                        <div class="card">
                            <div class="card-block">
                                <h6>Tariff Information</h6>
                                <div id="selected-procedure"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    pre {
        outline: 1px solid #ccc;
        padding: 5px;
        margin: 5px;
    }

    .string {
        color: green;
    }

    .number {
        color: darkorange;
    }

    .boolean {
        color: blue;
    }

    .null {
        color: magenta;
    }

    .key {
        color: red;
    }
</style>
<a class="hide" data-url="@Url.Action("Search", "Procedures")" id="dataURL"></a>
<a class="hide" data-url="@Url.Action("GetTariff", "Procedures")" id="tariffURL"></a>
@section scripts {
    <script>
        function Search() {
            $('#loading').removeClass('hide');
            $.ajax({
                type: 'POST',
                url: $('#dataURL').data('url'),
                data: '{ "legacyCode" : "' + $("#legacyCode").val() + '", "dependantId" : "' + $("#dependantId").val() + '", "providerId" : "' + $("#providerId").val() + '", "target" : "' + $("#target").val() + '" }',
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                success: function (data) {

                    $('#loading').addClass('hide');

                    var res = "";
                    data = $.parseJSON(data);
                    if (data.length > 0) {
                        for (var i = 0; i < data.length; i++) {
                            res += "<tr><td>" + data[i].procedureCode + "</td><td>" + data[i].procedureDesc + "</td><td><button class='btn btn-primary m-b-10 btn-sm waves-effect waves-light m-r-20' onclick='GetTariff(\"" + data[i].procedureCode + "\")'>Get Tariff</button></td></tr>";
                        }
                        $('#result').html(res);
                    }
                    else {
                        $('#result').html('<tr><td colspan="2">No records found!</td></tr>');
                    }
                }
            });
        }
        function GetTariff(code) {
            $('#loading').removeClass('hide');
            $.ajax({
                type: 'POST',
                url: $('#tariffURL').data('url'),
                data: '{ "legacyCode" : "' + $("#legacyCode").val() + '", "dependantId" : "' + $("#dependantId").val() + '", "providerId" : "' + $("#providerId").val() + '", "procedureCode" : "' + code + '" }',
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                success: function (data) {
                    data = $.parseJSON(data);
                    $('#loading').addClass('hide');
                    var res = "<table class='table table-striped'>" +
                        "<tr><td>Selected Procedure</td><td>" + data.procedureCode + "</td></tr>" +
                        "<tr><td>Tariff</td><td>" + data.tariff + "</td></tr>" +
                        "<tr><td>Narration</td><td style='white-space: pre-wrap;'>" + data.tariffInUse + "</td></tr>" +
                        "</table><br /><hr /><br />";
                    $('#selected-procedure').html(res);
                }
            });
        }
        function syntaxHighlight(json) {
            if (typeof json != 'string') {
                json = JSON.stringify(json, undefined, 2);
            }
            json = json.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
            return json.replace(/("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)/g, function (match) {
                var cls = 'number';
                if (/^"/.test(match)) {
                    if (/:$/.test(match)) {
                        cls = 'key';
                    } else {
                        cls = 'string';
                    }
                } else if (/true|false/.test(match)) {
                    cls = 'boolean';
                } else if (/null/.test(match)) {
                    cls = 'null';
                }
                return '<span class="' + cls + '">' + match + '</span>';
            });
        }
    </script>
}